const types = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_ADD_FAIL: 'CART_ADD_FAIL',
  SAVE_SHIPPING: 'SAVE_SHIPPING',
  SAVE_PAYMENT: "SAVE_PAYMENT",
  CLEAR_CART: 'CLEAR_CART'
}

export default types
