export const DASHBOARD_STATS_REQUEST = 'DASHBOARD_STATS_REQUEST'
export const DASHBOARD_STATS_SUCCESS = 'DASHBOARD_STATS_SUCCESS'
export const DASHBOARD_STATS_FAIL = 'DASHBOARD_STATS_FAIL'

export const DASHBOARD_LATESTORDERS_REQUEST = 'DASHBOARD_LATESTORDERS_REQUEST'
export const DASHBOARD_LATESTORDERS_SUCCESS = 'DASHBOARD_LATESTORDERS_SUCCESS'
export const DASHBOARD_LATESTORDERS_FAIL = 'DASHBOARD_LATESTORDERS_FAIL'

export const DASHBOARD_RECENTPRODUCTS_REQUEST = 'DASHBOARD_RECENTPRODUCTS_REQUEST'
export const DASHBOARD_RECENTPRODUCTS_SUCCESS = 'DASHBOARD_RECENTPRODUCTS_SUCCESS'
export const DASHBOARD_RECENTPRODUCTS_FAIL = 'DASHBOARD_RECENTPRODUCTS_FAIL'
